version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./packages/api:/app/packages/api
      - /app/packages/api/node_modules
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
